### ISSUE TITLE
no data_collection_pipeline

### ISSUE THREAD

**Issue by huifeng3** [GuanlinLee/ART#2] opened 2024-10-11 13:37 UTC
I want to generate my own datasets for llm and vlm by running craft_llm_dataset.py and craft_vlm_dataset.py. But it warned me that there's no module named data_collection_pipeline. Could u provide it 4 me : )

**Comment by GuanlinLee** [comment] 2024-10-11 13:40
Sorry for the code I have missed. I will fix it on Monday.

**Comment by GuanlinLee** [comment] 2024-10-14 05:50
The problem is fixed now. You can try to generate your datasets. It may take a very long time, due to the inference time of llama3-70b.

**Closed as completed by GuanlinLee** 2024-10-14 05:50 UTC
